setwd("~/Documents/R/chitest/data/")
print ("The CSV file should be named df.csv")
df <- read.csv("~/Documents/R/chitest/data/df.csv")
df$PosixDate <- as.POSIXct(strptime(df$Date, format="%m/%d/%Y %H:%M"))
save(df,file="crimestest.rda")